use std::path::Path;

use super::posix_quote::quote_executable;

pub fn init_code(binary: Option<&Path>) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let exe = match binary {
        Some(path) => format!("command {}", quote_executable(path)),
        None => "command shellenv".to_string(),
    };

    format!(
        r#"# Generated by shellenv {version}

shellenv_run() {{
    local profile="${{SHELLENV_PROFILE:-default}}"

    {exe} run \
        --profile "$profile" \
        --shell bash \
        -- "$@"
}}

shellenv_exec_agent() {{
    local profile="${{SHELLENV_PROFILE:-default}}"

    {exe} run \
        --profile "$profile" \
        --shell bash \
        --timeout-ms "${{SHELLENV_TIMEOUT_MS:-30000}}" \
        -- "$@"
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn init_code_contains_helpers_literal_shell_and_version() {
        let code = init_code(Some(Path::new("/opt/shellenv")));
        assert!(code.contains(&format!(
            "# Generated by shellenv {}",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(code.contains("shellenv_run()"));
        assert!(code.contains("shellenv_exec_agent()"));
        assert!(code.contains("--shell bash"));
        assert!(code.contains("--timeout-ms"));
        assert!(code.contains("30000"));
        assert!(code.contains("command '/opt/shellenv'"));
        assert!(!code.contains("local shell="));
    }

    #[test]
    fn fallback_uses_command_shellenv() {
        let code = init_code(None);
        assert!(code.contains("command shellenv"));
    }
}
