use std::path::Path;

pub fn init_code(binary: Option<&Path>) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let exe = match binary {
        Some(path) => format!("command {}", quote_executable(path)),
        None => "command shellenv".to_string(),
    };

    format!(
        r#"# Generated by shellenv {version}

function shellenv_run
    set -l profile (test -n "$SHELLENV_PROFILE"; and echo "$SHELLENV_PROFILE"; or echo "default")

    {exe} run \
        --profile $profile \
        --shell fish \
        -- $argv
end

function shellenv_exec_agent
    set -l profile (test -n "$SHELLENV_PROFILE"; and echo "$SHELLENV_PROFILE"; or echo "default")
    set -l timeout (test -n "$SHELLENV_TIMEOUT_MS"; and echo "$SHELLENV_TIMEOUT_MS"; or echo "30000")

    {exe} run \
        --profile $profile \
        --shell fish \
        --timeout-ms $timeout \
        -- $argv
end
"#
    )
}

fn quote_executable(path: &Path) -> String {
    let raw = path.to_string_lossy();
    let mut out = String::from("'");
    for ch in raw.chars() {
        if ch == '\'' {
            out.push_str("\\'");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn quote_executable_spaces_and_single_quotes() {
        assert_eq!(
            quote_executable(Path::new("/my tools/shellenv")),
            "'/my tools/shellenv'"
        );
        assert_eq!(
            quote_executable(Path::new("/tmp/foo'bar/shellenv")),
            "'/tmp/foo\\'bar/shellenv'"
        );
    }

    #[test]
    fn init_code_contains_helpers_literal_shell_and_version() {
        let code = init_code(Some(Path::new("/opt/shellenv")));
        assert!(code.contains(&format!(
            "# Generated by shellenv {}",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(code.contains("function shellenv_run"));
        assert!(code.contains("function shellenv_exec_agent"));
        assert!(code.contains("--shell fish"));
        assert!(code.contains("--timeout-ms"));
        assert!(code.contains("30000"));
        assert!(code.contains("command '/opt/shellenv'"));
        assert!(code.contains("-- $argv"));
        assert!(code.contains("test -n \"$SHELLENV_PROFILE\""));
        assert!(code.contains("test -n \"$SHELLENV_TIMEOUT_MS\""));
    }

    #[test]
    fn fallback_uses_command_shellenv() {
        let code = init_code(None);
        assert!(code.contains("command shellenv"));
    }

    #[test]
    fn init_code_quotes_paths_with_spaces_and_single_quotes() {
        let code = init_code(Some(Path::new("/my tools/shellenv")));
        assert!(code.contains("command '/my tools/shellenv'"));

        let code = init_code(Some(Path::new("/tmp/foo'bar/shellenv")));
        assert!(code.contains("command '/tmp/foo\\'bar/shellenv'"));
    }
}
