use std::path::Path;

pub fn init_code(binary: Option<&Path>) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let invocation = match binary {
        Some(path) => format!("& {}", quote_executable(path)),
        None => concat!(
            "$shellenvBinary = (Get-Command shellenv -CommandType Application ",
            "-ErrorAction Stop | Select-Object -First 1).Source\n    & $shellenvBinary"
        )
        .to_string(),
    };

    format!(
        r#"# Generated by shellenv {version}

function shellenv_run {{
    $shellenvProfile = if ($null -ne $env:SHELLENV_PROFILE -and $env:SHELLENV_PROFILE -ne '') {{
        $env:SHELLENV_PROFILE
    }} else {{
        "default"
    }}
    $shellenvArgs = $args

    {invocation} run --profile $shellenvProfile --shell pwsh -- @shellenvArgs
}}

function shellenv_exec_agent {{
    $shellenvProfile = if ($null -ne $env:SHELLENV_PROFILE -and $env:SHELLENV_PROFILE -ne '') {{
        $env:SHELLENV_PROFILE
    }} else {{
        "default"
    }}
    $shellenvTimeout = if ($null -ne $env:SHELLENV_TIMEOUT_MS -and $env:SHELLENV_TIMEOUT_MS -ne '') {{
        $env:SHELLENV_TIMEOUT_MS
    }} else {{
        "30000"
    }}
    $shellenvArgs = $args

    {invocation} run --profile $shellenvProfile --shell pwsh --timeout-ms $shellenvTimeout -- @shellenvArgs
}}
"#
    )
}

fn quote_executable(path: &Path) -> String {
    format!("'{}'", path.to_string_lossy().replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_code_contains_helpers_defaults_and_literal_shell() {
        let code = init_code(Some(Path::new("/opt/shellenv")));

        assert!(code.contains(&format!(
            "# Generated by shellenv {}",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(code.contains("function shellenv_run"));
        assert!(code.contains("function shellenv_exec_agent"));
        assert!(code.contains("--shell pwsh"));
        assert!(code.contains("--timeout-ms"));
        assert!(code.contains("30000"));
        assert!(code.contains("$shellenvProfile"));
        assert!(code.contains("$shellenvTimeout"));
        assert!(code.contains("$shellenvArgs = $args"));
        assert!(code.contains("@shellenvArgs"));
        assert!(!code.contains("$shellenvShell"));
        assert!(!code.contains("$profile ="));
        assert!(!code.contains("$PROFILE ="));
    }

    #[test]
    fn empty_environment_values_use_defaults_without_trimming_whitespace() {
        let code = init_code(Some(Path::new("/opt/shellenv")));

        assert!(code.contains("$env:SHELLENV_PROFILE -ne ''"));
        assert!(code.contains("$env:SHELLENV_TIMEOUT_MS -ne ''"));
        assert!(!code.contains(".Trim()"));
        assert!(!code.contains("IsNullOrWhiteSpace"));
    }

    #[test]
    fn absolute_binary_uses_call_operator_and_powershell_quoting() {
        let code = init_code(Some(Path::new("/my tools/foo'bar/shellenv")));

        assert!(code.contains("& '/my tools/foo''bar/shellenv' run"));
    }

    #[test]
    fn fallback_resolves_an_application_before_invocation() {
        let code = init_code(None);

        assert!(code.contains("Get-Command shellenv -CommandType Application"));
        assert!(code.contains("Select-Object -First 1"));
        assert!(code.contains("& $shellenvBinary run"));
        assert!(!code.contains("& shellenv run"));
    }
}
